### ISSUE TITLE
Error converting model to tflite

### ISSUE THREAD

**Issue by raghavgurbaxani** [tulasiram58827/craft_tflite#3]
Hi @tulasiram58827 

Thank you for your great work. When I run your colab notebook CRAFT_TFLITE.ipynb. I get the following error - 

`
ConverterError: /usr/local/lib/python3.6/dist-packages/tensorflow/python/saved_model/load.py:890:0: error: 'tf.MaxPool' op is neither a custom op nor a flex op`

Do you know how to get around it ? Thanks

**Comment by tulasiram58827** [comment]
@raghavgurbaxani  You can try using `tf-nightly` it will be solved. I tried myself with `tf-nightly` it is working. Let me know still if you have any issue.

**Comment by raghavgurbaxani** [comment]
Hi @tulasiram58827 
Thank you, I am trying to convert a tflite model using float 16 and 640x480 input, but I get the following error - 

`RuntimeError: tensorflow/lite/kernels/concatenation.cc:73 t->dims->data[d] != t0->dims->data[d] (30 != 28)Node number 167 (CONCATENATION) failed to prepare.`

![image](https://user-images.githubusercontent.com/32988039/105251582-ad5c5780-5b30-11eb-98e7-c88e97683949.png)

caused by` y, feature = run_tflite_model(x)`

any clue whats going wrong ?

**Comment by tulasiram58827** [comment]
Are you using `tf-nightly`?

**Comment by raghavgurbaxani** [comment]
@tulasiram58827 yeah I am , please find collab notebook [here](https://colab.research.google.com/drive/1slj7OwIZ8M567BDUyNLUI7w-Eag7b55R?usp=sharing) 

Thanks again

**Comment by tulasiram58827** [comment]
Hey, @raghavgurbaxani I just found out that this is due to the TensorFlow version compatibility problem. Model conversion working with `tensorflow==2.3.0` and `tf-nightly`. Model inference working with only `tensorflow==2.3.0`. As the default version of colab notebook is now `tensorflow==2.4.1` so the inference is not working. I will report this to the TFLite team.

You need to install `tensorflow==2.3.0` using this command at the start of this notebook `pip install tensorflow==2.3.0` everything works as usual. I will be committing the fix soon.

**Comment by tulasiram58827** [comment]
From TFLite team
> TFLite's MaxPool op kernel does not support all inputs like the model's inputs in the gist. However, the older versions converted them without checking its capability to TFLite MaxPool operator. That was wrong behavior. To reflect the capability of the TFLite MaxPool, the select TF option is needed since the TFLite MaxPool can not handle those inputs and it should select the fallback option via the select TF option.

I committed the fix you can use the new notebook committed.
